### ISSUE TITLE
add_MARBL (compute): final checklist for initial MARBL driver

### ISSUE THREAD

**Issue by mnlevy1981** [mnlevy1981/MOM6#76]
One last checklist of tasks before we can seriously consider merging with `dev/ncar`. These don't warrant issue tickets on their own, but may spawn issue tickets as we try to complete them:

- [x] Run on new `tx2_3v2` grid
- [x] Get `abio` module working (need ICs and one forcing field); may get us most of the way to `ciso` module as well
- [x] Run with hybrid vertical coordinate (hycom?)
- [x] Run fully-coupled
- [ ] Make sure code follows [style guide](https://github.com/mom-ocean/MOM6/wiki/Code-style-guide)

**Comment by mnlevy1981** [comment]
I'm pretty sure there are one or two more tasks I've been thinking need to be finished; when I remember them I'll update the list in the comment above

**Comment by mnlevy1981** [comment]
`tx2_3v2` support came in mid-December, hybrid coordinates in late December / mid-January, `abio` in late January, and all the forcing files for fully coupled were available early February.

**Comment by mnlevy1981** [comment]
Bringing in the MARBL driver will obviously require PRs for both MOM6 and MOM_interface. Per #77, there are also changes necessary in CMEPS... and I also made the following changes in FMS:

```diff
diff --git a/diag_manager/diag_data.F90 b/diag_manager/diag_data.F90
index a1f59470..69a97351 100644
--- a/diag_manager/diag_data.F90
+++ b/diag_manager/diag_data.F90
@@ -64,7 +64,7 @@ MODULE diag_data_mod
   PUBLIC

   ! Specify storage limits for fixed size tables used for pointers, etc.
-  INTEGER, PARAMETER :: MAX_FIELDS_PER_FILE = 300 !< Maximum number of fields per file.
+  INTEGER, PARAMETER :: MAX_FIELDS_PER_FILE = 400 !< Maximum number of fields per file.
   INTEGER, PARAMETER :: DIAG_OTHER = 0
   INTEGER, PARAMETER :: DIAG_OCEAN = 1
   INTEGER, PARAMETER :: DIAG_ALL   = 2
@@ -297,7 +297,7 @@ MODULE diag_data_mod
   ! <!-- Namelist variables -->
   LOGICAL :: append_pelist_name = .FALSE.
   LOGICAL :: mix_snapshot_average_fields =.FALSE.
-  INTEGER :: max_files = 31 !< Maximum number of output files allowed.  Increase via diag_manager_nml.
+  INTEGER :: max_files = 40 !< Maximum number of output files allowed.  Increase via diag_manager_nml.
   INTEGER :: max_output_fields = 300 !< Maximum number of output fields.  Increase via diag_manager_nml.
   INTEGER :: max_input_fields = 600 !< Maximum number of input fields.  Increase via diag_manager_nml.
   INTEGER :: max_out_per_in_field = 150 !< Maximum number of output_fields per input_field.  Increase
```

Before updating FMS, though, I want to test the MARBL driver with the default FMS configuration -- I believe these changes are necessary if we want 3D MARBL output on the native grid and also interpolated to a z-grid
